# External Secret for ConfigMap values (non-sensitive)
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fast-food-api-config
  namespace: fast-food-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: fast-food-api-config
    type: Opaque
  data:
    # Application configuration (non-sensitive)
    - secretKey: NODE_ENV
      remoteRef:
        key: fast-food-api-node-env
    - secretKey: PORT
      remoteRef:
        key: fast-food-api-port
    - secretKey: LOG_LEVEL
      remoteRef:
        key: fast-food-api-log-level
    - secretKey: CORS_ORIGIN
      remoteRef:
        key: fast-food-api-cors-origin
    - secretKey: DATABASE_HOST
      remoteRef:
        key: fast-food-api-database-host
    - secretKey: DATABASE_PORT
      remoteRef:
        key: fast-food-api-database-port
    - secretKey: DATABASE_NAME
      remoteRef:
        key: fast-food-api-database-name
    - secretKey: MERCADO_PAGO_WEBHOOK_URL
      remoteRef:
        key: fast-food-api-webhook-url
---
# External Secret for sensitive values
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fast-food-api-secrets
  namespace: fast-food-api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: fast-food-api-secrets
    type: Opaque
  data:
    # Database configuration (sensitive)
    - secretKey: DATABASE_USER
      remoteRef:
        key: fast-food-api-database-user
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: fast-food-api-database-password
    - secretKey: DATABASE_URL
      remoteRef:
        key: fast-food-api-database-url

    # External services (sensitive)
    - secretKey: MERCADO_PAGO_ACCESS_TOKEN
      remoteRef:
        key: fast-food-api-mercado-pago-token
    - secretKey: MERCADO_PAGO_PUBLIC_KEY
      remoteRef:
        key: fast-food-api-mercado-pago-key
    - secretKey: JWT_SECRET
      remoteRef:
        key: fast-food-api-jwt-secret
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: fast-food-api
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      vaultUrl: ${AZURE_KEY_VAULT_URL}
      tenantId: ${AZURE_TENANT_ID}
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: client-id
        clientSecret:
          name: azure-secret-sp
          key: client-secret
