apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-api-deployment
  namespace: fast-food-api
  labels:
    app: fast-food-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-food-api
  template:
    metadata:
      labels:
        app: fast-food-api
    spec:
      containers:
        - name: fast-food-api
          image: fast-food-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: PORT
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: LOG_LEVEL
            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: CORS_ORIGIN
            - name: DATABASE_URL
              value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)"
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: fast-food-api-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fast-food-api-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: fast-food-api-config
                  key: DATABASE_NAME
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fast-food-api-secrets
                  key: MERCADO_PAGO_ACCESS_TOKEN
            - name: MERCADO_PAGO_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: fast-food-api-secrets
                  key: MERCADO_PAGO_PUBLIC_KEY
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: fast-food-api-secrets
                  key: WEBHOOK_SECRET
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
