kind: Namespace
metadata:
  name: fast-food-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-food-api
  namespace: fast-food-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-food-api
  template:
    metadata:
      labels:
        app: fast-food-api
    spec:
      containers:
      - name: fast-food-api
        image: fast-food-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@host.minikube.internal:5432/fastfood"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fast-food-api-service
  namespace: fast-food-api
spec:
  selector:
    app: fast-food-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP