apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fast-food-api

resources:
  - base
  - networking/network-policy.yaml
  - networking/ingress.yaml
  - scaling/hpa.yaml

commonLabels:
  app: fast-food-api
  version: v1.0.0
  environment: production
