apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fast-food-api-dev

resources:
  - ../../

patches:
  - target:
      kind: Deployment
      name: fast-food-api-deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: "128Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "100m"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: "256Mi"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "200m"

  - target:
      kind: HorizontalPodAutoscaler
      name: fast-food-api-hpa
    patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 1
      - op: replace
        path: /spec/maxReplicas
        value: 3

  - target:
      kind: ConfigMap
      name: fast-food-api-config
    patch: |-
      - op: replace
        path: /data/NODE_ENV
        value: "development"
      - op: replace
        path: /data/LOG_LEVEL
        value: "debug"

commonLabels:
  environment: development
